apply plugin: 'maven-publish'

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId releaseGroupId
                artifactId releaseArtifactId
                version releaseVersion

                artifact("$buildDir/outputs/aar/${project.name}-release.aar")
            }
        }
    }
}